name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
      - 'feature/**'
  workflow_dispatch:

jobs:
  build:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_flight_booking
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DB_USER: test_user
      DB_PASSWORD: test_password
      DB_HOST: localhost
      DB_NAME: test_flight_booking
      DB_PORT: 5433
      PORT: 5004

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd backend
          npm install

      - name: Seed Test Database
        run: |
          cd backend/scripts
          node seedTestDb.js

      - name: Run Backend Tests
        run: |
          cd backend
          PORT=5004 npm test

      - name: Build Docker Image
        run: |
          cd backend
          docker build -t flight-booking-backend .

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: |
          cd backend
          docker-compose up -d

      - name: Show Logs on Failure
        if: failure()
        run: |
          docker logs flight_booking_backend